### ISSUE TITLE
5.1.0 and 5.1.1 yanked upstream

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nbformat-feedstock#24]
It looks like `5.1.0` and `5.1.1` are both known-bad:

![Screenshot from 2021-01-14 20-54-10](https://user-images.githubusercontent.com/45380/104670883-aeae0000-56aa-11eb-8b27-03320a21021a.png)

Just wanted to have this reference point for 
- #21 maybe shouldn't have been merged
- #22 (5.1.1) is also broken, and _definitely_ shouldn't be merged
- #23 adds tests that would have caught #21

...and a forthcoming admin request...

**Comment by bollwyvl** [comment]
`5.1.0` is now marked broken, so should no longer cause anybody problems (unless they already it installed, via pip or something, that can't be managed):

https://github.com/conda-forge/admin-requests/pull/216

**Comment by jakirkham** [comment]
Should we close out PR ( https://github.com/conda-forge/nbformat-feedstock/pull/22 ) then?

**Comment by bollwyvl** [comment]
Yeah, #22 was bunk.

We got #25 in, but it means that if some some upstream packaging issue hits us, we won't know. I've updated #23.

**Comment by ocefpaf** [comment]
Thanks for taking care if this @bollwyvl!

**Comment by bollwyvl** [comment]
Nobody has complained about those couple bad versions, closing this!
